
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
    volumes:
      - db_data:/var/lib/mysql
      # Initial database dump for initialization
      - ./sql/setup_ps_uu_periegesis.sql:/docker-entrypoint-initdb.d/setup_ps_uu_periegesis.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    restart: always
    ports:
      - "8044:80"
    environment:
      - DB_HOST=db
      - DB_NAME=
      - DB_USER=
      - DB_PASS=
      - DB_CHARSET=utf8mb4
      - SITE_SOCKET=http://
      - SITE_URL=
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
