[
{"title": "Image-Caption Center", "description": "Image with Caption - Text is placed before and after the image", "url": "tinymce/templates/figure_center.htm"},
{"title": "Image-Caption Left", "description": "Image with Caption - Text is placed on the Right of the image", "url": "tinymce/templates/figure_left.htm"},
{"title": "Image-Caption Right", "description": "Image with Caption - Text is placed on the Left of the image", "url": "tinymce/templates/figure_right.htm"},
{"title": "Images in Table Top", "description": "Images in First row, Text in Next", "url": "tinymce/templates/image_in_table_top.htm"},
{"title": "Images in Table Left", "description": "Images with same width on the Left", "url": "tinymce/templates/image_in_table_left.htm"},
{"title": "Images in Table Right", "description": "Images with same width on the Left", "url": "tinymce/templates/image_in_table_right.htm"},
{"title": "Background Center", "description": "Centered Text in gray background color", "url": "tinymce/templates/bg_center.htm"},
{"title": "Background Left", "description": "Left Text in gray background color", "url": "tinymce/templates/bg_left.htm"},
{"title": "Background Right", "description": "Right Text in gray background color", "url": "tinymce/templates/bg_right.htm"},
{"title": "Table - No Headers", "description": "Table with 3 Columns", "url": "tinymce/templates/table_NoHeaders.htm"},
{"title": "Table - Top Headers", "description": "Table with Headers on Top", "url": "tinymce/templates/table_HeadTop.htm"},
{"title": "Table - Left Headers", "description": "Table with Headers on Left", "url": "tinymce/templates/table_HeadLeft.htm"},
{"title": "YouTube Embed Center", "description": "Change the crs of the embeded URL to YouTube", "url": "tinymce/templates/object_youtube.htm"},
{"title": "YouTube Embed Left", "description": "Change the crs of the embeded URL to YouTube", "url": "tinymce/templates/object_youtube_left.htm"},
{"title": "Video MP4/OGG Center", "description": "Change the Source (crs) - media type .mp4 and .ogg", "url": "tinymce/templates/object_video.htm"},
{"title": "Video MP4/OGG Left", "description": "Change the Source (crs) - media type .mp4 and .ogg", "url": "tinymce/templates/object_video_left.htm"},
{"title": "Audio-Music MP3/OGG Center", "description": "Change the Source (crs) - media type .mp3, .mpeg and .ogg", "url": "tinymce/templates/object_audio.htm"},
{"title": "Audio-Music MP3/OGG Left", "description": "Change the Source (crs) - media type .mp3, .mpeg and .ogg", "url": "tinymce/templates/object_audio_left.htm"},
{"title": "Poems marked by Rows", "description": "Poems where every 5th Number of Rows, marked as strong, excedes to the left", "url": "tinymce/templates/poem_numbers.htm"}
]