<?php

//PHP CAPTCHA image
//Generated by https://www.html-code-generator.com/php/captcha-image-code-generator.php

session_start();

$width = 200;
$height = 60;
$font_size = 26;
/*
$font = realpath(dirname(__DIR__)).'/captcha/fonts/Alam_font.ttf';
$font = realpath(dirname(__DIR__)).'/captcha/fonts/DejaVuSans-Bold.ttf';
$font = realpath(dirname(__DIR__)).'/captcha/fonts/DejaVuSans-ExtraLight.ttf';
$font = realpath(dirname(__DIR__)).'/captcha/fonts/DejaVuSerif-Bold.ttf';
$font = realpath(dirname(__DIR__)).'/captcha/fonts/DejaVuSerif-Italic.ttf';
$font = realpath(dirname(__DIR__)).'/captcha/fonts/monofont.ttf';
$font = realpath(dirname(__DIR__)).'/captcha/fonts/TheanoDidot-Regular.ttf';
$font = realpath(dirname(__DIR__)).'/captcha/fonts/TheanoModern-Regular.ttf';
$font = realpath(dirname(__DIR__)).'/captcha/fonts/Tinos-Italic.ttf';
*/
$font = realpath(dirname(__DIR__)) . '/captcha/fonts/DejaVuSerif-Bold.ttf';
$chars_length = 5;

//$captcha_characters = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
$captcha_characters = "abcdefghjkmnopqrstuvwxyz23456789ABDEFGHLMNQRT";

$image = imagecreatetruecolor($width, $height);
$bg_color = imagecolorallocate($image, rand(0, 102), rand(0, 102), rand(0, 102));
imagefilledrectangle($image, 0, 0, $width, $height, $bg_color);

//background random-line
$vert_line = round($width / 5);
for ($i = 0; $i < $vert_line; $i++) {
    $color = imagecolorallocate($image, rand(153, 255), rand(153, 255), rand(153, 255));
    imageline($image, rand(0, $width), rand(0, $height), rand(0, $height), rand(0, $width), $color);
}

$xw = (int) ($width / $chars_length);
$font_gap = (int) ($xw / 2 - $font_size / 2);
$x = 0;
$digit = '';
for ($i = 0; $i < $chars_length; $i++) {
    $letter = $captcha_characters[rand(0, strlen($captcha_characters) - 1)];
    $digit .= $letter;
    $font_color = imagecolorallocate($image, rand(204, 255), rand(204, 255), rand(204, 255));
    if ($i == 0) {
        $x = 0;
    } else {
        $x = $xw * $i;
    }
    imagettftext($image, $font_size, rand(-20, 20), $x + $font_gap, rand(28, $height - 8), $font_color, $font, $letter);
}

// record token in session variable
$_SESSION['captcha_code'] = strtolower($digit);

// display image
header('Content-Type: image/png');
imagepng($image);
imagedestroy($image);
